# Generated by Django 6.0.7 on 2026-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcampaign",
            name="channel",
            field=models.CharField(
                choices=[
                    ("Яндекс.Директ", "Яндекс.Директ"),
                    ("ВКонтакте", "ВКонтакте"),
                    ("Google Ads", "Google Ads"),
                    ("Telegram", "Telegram"),
                ],
                max_length=255,
                verbose_name="Канал продвижения",
            ),
        ),
    ]
