# Generated by Django 6.0.7 on 2026-07-20 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_adcampaign_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcampaign",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Бюджет",
            ),
        ),
    ]
