# Generated by Django 6.0.7 on 2026-07-20 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="full_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ф.И.О должно быть в формате: Иванов Иван Иванович",
                        regex="^[А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+$",
                    )
                ],
                verbose_name="Ф.И.О",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона в формате: +71234567890",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: +71234567890",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
