# Generated by Django 6.0.7 on 2026-07-20 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_email_alter_lead_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: +71234567890",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
