# Generated by Django 6.0.7 on 2026-07-20 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Период действия (дней)",
            ),
        ),
    ]
