# Generated by Django 6.0.7 on 2026-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contract_amount_alter_contract_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Период действия (дней)"),
        ),
    ]
